name: Code Quality Check

on:
  push:
    branches:
      - dev

jobs:
  code_quality:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install flake8
      - name: Run Flake8
        run: flake8
